version: "3.3"
services:
  immuclient:
    image: nginx:alpine
    container_name: "immuclient"
    ports:
      - 8085:80
    volumes:
      - ./web/public:/srv/www
      - ./web/conf/default.conf:/etc/nginx/conf.d/default.conf
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8084:8080"
    volumes:
      - ./pkg/api/schema.swagger.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
  immud:
    image: immud
    build: https://github.com/codenotary/immudb.git#feat/safesetget
    container_name: immud
    command: "immud --address immud --directory immudb-data --name demo"
    volumes:
      - ./immudb-data:/immudb-data
    ports:
      - "8083:8080"
  immurestproxy:
    image: immurestproxy
    container_name: immurestproxy
    build:
      context: ./
    ports:
      - "8081:8081"
